//
//  Neighborhoods.swift
//  Cheers
//
//  Created by Meelad Dawood on 3/15/18.
//  Copyright © 2018 University of San Diego. All rights reserved.
//

import Foundation

enum Neighborhood: String, Codable {
    case BalboaPark = "Balboa Park"
    case BankersHill = "Banker's Hill"
    case BayBark = "Bay Park"
    case Bonita = "Bonita"
    case Cardiff = "Cardiff"
    case Carlsbad = "Carlsbad"
    case CarmelMountainRanch = "Carmel Mountain Ranch"
    case CarmelValley = "Carmel Valley"
    case ChulaVista = "Chula Vista"
    case Clairemont = "Clairemont"
    case College = "College"
    case Coronado = "Coronado"
    case DelMar = "Del Mar"
    case Downtown = "Downtown"
    case Eastlake = "Eastlake"
    case EastVillage = "East Village"
    case ElCajon = "El Cajon"
    case Encinitas = "Encinitas"
    case Escondido = "Escondido"
    case FourSRanch = "4S Ranch"
    case GaslampQuarter = "Gaslamp Quarter"
    case Grantville = "Grantville"
    case HarborIsland = "Harbor Island"
    case Hillcrest = "Hillcrest"
    case ImperialBeach = "Imperial Beach"
    case KearnyMesa = "Kearny Mesa"
    case Kensington = "Kensington"
    case LaJolla = "La Jolla"
    case LaMesa = "La Mesa"
    case Leucadia = "Leucadia"
    case LindaVista = "Linda Vista"
    case LittleItaly = "Little Italy"
    case MarinaDistrict = "Marina District"
    case Middletown = "Middletown"
    case MidwayDistrict = "Midway District"
    case MiraMesa = "Mira Mesa"
    case MissionBeach = "Mission Beach"
    case MissionValley = "Mission Valley"
    case MorenaDistrict = "Morena District"
    case NationalCity = "National City"
    case NormalHeights = "Normal Heights"
    case NorthPark = "North Park"
    case OceanBeach = "Ocean Beach"
    case Oceanside = "Oceanside"
    case OldTown = "Old Town"
    case PacificBeach = "Pacific Beach"
    case PointLoma = "Point Loma"
    case Poway = "Poway"
    case RanchoPenasquitos = "Rancho Penasquitos"
    case RanchoSanDiego = "Rancho San Diego"
    case SanMarcos = "San Marcos"
    case Santee = "Santee"
    case ScrippsRanch = "Scripps Ranch"
    case SerraMesa = "Serra Mesa"
    case ShelterIsland = "Shelter Island"
    case SolanaBeach = "Solana Beach"
    case SorrentoValley = "Sorrento Valley"
    case SouthPark = "South Park"
    case SpringValley = "Spring Valley"
    case UnivesrityCity = "University City"
    case UniversityHeights = "University Heights"
    case Vista = "Vista"
    
    case unknown = ""
    
}
